[platformio]
src_dir = src
include_dir = include

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    hamzayslmn/esp-ps5 @ ^1.3.3
    https://github.com/eagletrt/libpid-sw